// --- HEALTHVERSE AI STATE MANAGEMENT ---

const DEFAULT_STATE = {
  profile: null, // User details
  dailyIntake: {
    calories: 0,
    protein: 0,
    carbs: 0,
    fats: 0,
    lastReset: null // Reset daily macros on next day
  },
  meals: [], // { name: '', calories: 0, protein: 0, carbs: 0, fats: 0, timestamp: Date, image: '' }
  workouts: [], // { title: '', exercisesCount: 0, durationMinutes: 0, timestamp: Date }
  weightLogs: [], // { weight: 0, date: 'YYYY-MM-DD' }
  customRoutine: null, // Generated by AI
  activeWorkout: null, // Current workout progress
  theme: 'light' // Theme mode: 'light' or 'dark'
};

let appState = { ...DEFAULT_STATE };

// Load State from LocalStorage
function loadState() {
  const data = localStorage.getItem('healthverse_state');
  if (data) {
    try {
      appState = JSON.parse(data);
      if (!appState.theme) {
        appState.theme = 'light';
      }
      checkDailyReset();
    } catch (e) {
      console.error("Error parsing stored state, resetting to default.", e);
      appState = { ...DEFAULT_STATE };
    }
  } else {
    // Fresh run: Seed some sample logs to make charts immediately impressive
    appState = { ...DEFAULT_STATE };
    seedSampleData();
  }
}

// Save State to LocalStorage
function saveState() {
  localStorage.setItem('healthverse_state', JSON.stringify(appState));
}

// Theme application
function applyTheme() {
  const isDark = appState.theme === 'dark';
  if (isDark) {
    document.body.classList.add('dark-theme');
  } else {
    document.body.classList.remove('dark-theme');
  }
}

// Initialize Theme Toggle button listeners
function initThemeToggle() {
  const toggleBtn = document.getElementById('theme-toggle-btn');
  if (!toggleBtn) return;
  
  toggleBtn.addEventListener('click', () => {
    appState.theme = appState.theme === 'dark' ? 'light' : 'dark';
    saveState();
    applyTheme();
    
    // Re-render charts if analytics panel is open
    const activePanel = document.querySelector('.view-panel.active');
    if (activePanel && activePanel.id === 'analytics-panel') {
      renderCharts();
    }
  });
}

// Reset daily numbers if it's a new day
function checkDailyReset() {
  const todayStr = new Date().toDateString();
  if (appState.dailyIntake.lastReset !== todayStr) {
    appState.dailyIntake.calories = 0;
    appState.dailyIntake.protein = 0;
    appState.dailyIntake.carbs = 0;
    appState.dailyIntake.fats = 0;
    appState.dailyIntake.lastReset = todayStr;
    saveState();
  }
}

// Seed sample progress data if no profile is set yet
function seedSampleData() {
  const now = new Date();
  
  // Weights (last 7 days)
  appState.weightLogs = [];
  for (let i = 6; i >= 0; i--) {
    const d = new Date(now);
    d.setDate(now.getDate() - i);
    appState.weightLogs.push({
      weight: 78.5 - (i * 0.15) + (Math.sin(i) * 0.1),
      date: d.toISOString().split('T')[0]
    });
  }

  // Sample Meals
  appState.meals = [
    { name: "Avocado Toast with Egg", calories: 380, protein: 14, carbs: 42, fats: 18, timestamp: new Date(now - 3 * 3600000).toISOString() },
    { name: "Chicken and Brown Rice", calories: 520, protein: 42, carbs: 55, fats: 12, timestamp: new Date(now - 8 * 3600000).toISOString() }
  ];

  // Sample Workouts
  appState.workouts = [
    { title: "Upper Body Hypertrophy", exercisesCount: 5, durationMinutes: 48, timestamp: new Date(now - 24 * 3600000).toISOString() },
    { title: "HIIT Core Conditioning", exercisesCount: 6, durationMinutes: 30, timestamp: new Date(now - 48 * 3600000).toISOString() }
  ];

  appState.dailyIntake.lastReset = now.toDateString();
}

// Reset ALL State data
function resetAllData() {
  localStorage.removeItem('healthverse_state');
  appState = { ...DEFAULT_STATE };
  seedSampleData();
  saveState();
  window.location.reload();
}


// --- FORMULAS & TARGET CALCULATIONS ---

function calculateMetrics(age, gender, height, weight, activityLevel, goal) {
  // BMI = kg / m^2
  const heightMeters = height / 100;
  const bmi = weight / (heightMeters * heightMeters);

  // BMR (Mifflin-St Jeor Equation)
  let bmr = 0;
  if (gender === 'male') {
    bmr = 10 * weight + 6.25 * height - 5 * age + 5;
  } else {
    bmr = 10 * weight + 6.25 * height - 5 * age - 161;
  }

  // TDEE (Total Daily Energy Expenditure) multiplier
  const activityMultipliers = {
    sedentary: 1.2,
    light: 1.375,
    moderate: 1.55,
    active: 1.725,
    extreme: 1.9
  };
  const tdee = bmr * (activityMultipliers[activityLevel] || 1.2);

  // Calorie Target based on goal
  let targetCalories = tdee;
  if (goal === 'lose_fat') {
    targetCalories = tdee - 500; // Deficit
    if (targetCalories < 1200) targetCalories = 1200; // Health safety limit
  } else if (goal === 'gain_muscle') {
    targetCalories = tdee + 350; // Surplus
  } else if (goal === 'endurance') {
    targetCalories = tdee + 250;
  }

  // Macro Distributions (percentage of calories)
  let pPct = 0.25, cPct = 0.50, fPct = 0.25; // Default Balanced
  
  if (goal === 'lose_fat') {
    pPct = 0.35; cPct = 0.40; fPct = 0.25; // Higher protein, lower carbs
  } else if (goal === 'gain_muscle') {
    pPct = 0.30; cPct = 0.45; fPct = 0.25; // High carb/protein mix
  } else if (goal === 'endurance') {
    pPct = 0.20; cPct = 0.55; fPct = 0.25; // Extra carbs for energy
  }

  // 1g Protein = 4 kcal, 1g Carb = 4 kcal, 1g Fat = 9 kcal
  const targetProtein = Math.round((targetCalories * pPct) / 4);
  const targetCarbs = Math.round((targetCalories * cPct) / 4);
  const targetFats = Math.round((targetCalories * fPct) / 9);

  return {
    bmi: Math.round(bmi * 10) / 10,
    bmr: Math.round(bmr),
    tdee: Math.round(tdee),
    targetCalories: Math.round(targetCalories),
    targetProtein,
    targetCarbs,
    targetFats
  };
}


// --- AI WORKOUT GENERATION ENGINE ---

const WORKOUT_TEMPLATES = {
  lose_fat: [
    {
      day: "Day 1",
      name: "HIIT Full Body Blast",
      exercises: [
        { name: "Jumping Jacks", sets: 4, reps: "45 sec", rest: "15 sec", category: "Cardio" },
        { name: "Bodyweight Squats", sets: 3, reps: "15 reps", rest: "30 sec", category: "Strength" },
        { name: "Push-ups (or Knee Push-ups)", sets: 3, reps: "12 reps", rest: "30 sec", category: "Strength" },
        { name: "Mountain Climbers", sets: 4, reps: "40 sec", rest: "20 sec", category: "Cardio" },
        { name: "Plank Hold", sets: 3, reps: "60 sec", rest: "30 sec", category: "Core" }
      ]
    },
    {
      day: "Day 2",
      name: "Lower Body Conditioning",
      exercises: [
        { name: "Walking Lunges", sets: 3, reps: "12 per leg", rest: "30 sec", category: "Strength" },
        { name: "Glute Bridges", sets: 3, reps: "15 reps", rest: "30 sec", category: "Strength" },
        { name: "Kettlebell (or Dumbbell) Swings", sets: 4, reps: "20 reps", rest: "45 sec", category: "Power" },
        { name: "Burpees", sets: 3, reps: "10 reps", rest: "45 sec", category: "Cardio" },
        { name: "Bicycle Crunches", sets: 3, reps: "20 reps", rest: "30 sec", category: "Core" }
      ]
    },
    {
      day: "Day 3",
      name: "Cardio Kick & Core Devastator",
      exercises: [
        { name: "Shadow Boxing", sets: 3, reps: "60 sec", rest: "20 sec", category: "Cardio" },
        { name: "High Knees", sets: 4, reps: "45 sec", rest: "15 sec", category: "Cardio" },
        { name: "Dumbbell Thrusters", sets: 3, reps: "12 reps", rest: "45 sec", category: "Strength" },
        { name: "Russian Twists", sets: 3, reps: "20 reps", rest: "30 sec", category: "Core" },
        { name: "Flutter Kicks", sets: 3, reps: "45 sec", rest: "20 sec", category: "Core" }
      ]
    }
  ],
  gain_muscle: [
    {
      day: "Day 1",
      name: "Hypertrophy Push Day",
      exercises: [
        { name: "Dumbbell Chest Press", sets: 4, reps: "10 reps", rest: "60 sec", category: "Strength" },
        { name: "Overhead Shoulder Press", sets: 3, reps: "10 reps", rest: "60 sec", category: "Strength" },
        { name: "Incline Dumbbell Flyes", sets: 3, reps: "12 reps", rest: "45 sec", category: "Strength" },
        { name: "Triceps Overhead Extension", sets: 3, reps: "12 reps", rest: "45 sec", category: "Strength" },
        { name: "Lateral Raises", sets: 4, reps: "15 reps", rest: "45 sec", category: "Strength" }
      ]
    },
    {
      day: "Day 2",
      name: "Hypertrophy Pull Day",
      exercises: [
        { name: "Dumbbell Single-Arm Rows", sets: 4, reps: "10 per arm", rest: "60 sec", category: "Strength" },
        { name: "Pull-ups (or Lat Pulldowns)", sets: 4, reps: "8-10 reps", rest: "60 sec", category: "Strength" },
        { name: "Dumbbell Bicep Hammer Curls", sets: 3, reps: "12 reps", rest: "45 sec", category: "Strength" },
        { name: "Rear Delt Flyes", sets: 3, reps: "15 reps", rest: "45 sec", category: "Strength" },
        { name: "Barbell (or Dumbbell) Shrugs", sets: 3, reps: "12 reps", rest: "45 sec", category: "Strength" }
      ]
    },
    {
      day: "Day 3",
      name: "Lower Body Heavy Growth",
      exercises: [
        { name: "Goblet squats", sets: 4, reps: "12 reps", rest: "60 sec", category: "Strength" },
        { name: "Romanian Deadlifts (Dumbbell)", sets: 4, reps: "10 reps", rest: "60 sec", category: "Strength" },
        { name: "Walking Lunges (Weighted)", sets: 3, reps: "10 per leg", rest: "45 sec", category: "Strength" },
        { name: "Calf Raises", sets: 4, reps: "20 reps", rest: "30 sec", category: "Strength" },
        { name: "Hanging Leg Raises", sets: 3, reps: "12 reps", rest: "45 sec", category: "Core" }
      ]
    }
  ],
  active_lifestyle: [
    {
      day: "Day 1",
      name: "Total Body Mobility & Tone",
      exercises: [
        { name: "Cat-Cow Stretch", sets: 2, reps: "60 sec", rest: "10 sec", category: "Mobility" },
        { name: "Bodyweight Squats", sets: 3, reps: "15 reps", rest: "30 sec", category: "Strength" },
        { name: "Dumbbell Rows", sets: 3, reps: "12 reps", rest: "45 sec", category: "Strength" },
        { name: "Glute Bridge Hold", sets: 3, reps: "30 sec", rest: "30 sec", category: "Strength" },
        { name: "Bird-Dog Core Hold", sets: 3, reps: "10 per side", rest: "20 sec", category: "Core" }
      ]
    },
    {
      day: "Day 2",
      name: "Steady Heart & Lung Health",
      exercises: [
        { name: "Brisk Walk or Jog", sets: 1, reps: "20 min", rest: "None", category: "Cardio" },
        { name: "Step-ups", sets: 3, reps: "12 per leg", rest: "30 sec", category: "Strength" },
        { name: "Light Push-ups", sets: 3, reps: "10 reps", rest: "30 sec", category: "Strength" },
        { name: "Superman Holds", sets: 3, reps: "10 reps", rest: "20 sec", category: "Mobility" },
        { name: "Side Planks", sets: 2, reps: "30 sec per side", rest: "30 sec", category: "Core" }
      ]
    },
    {
      day: "Day 3",
      name: "Mindful Yoga Flow & Flex",
      exercises: [
        { name: "Downward Facing Dog", sets: 3, reps: "45 sec hold", rest: "15 sec", category: "Mobility" },
        { name: "Warrior II Pose", sets: 2, reps: "30 sec per side", rest: "10 sec", category: "Mobility" },
        { name: "Cobra Pose", sets: 3, reps: "30 sec hold", rest: "15 sec", category: "Mobility" },
        { name: "Child's Pose", sets: 1, reps: "2 min hold", rest: "None", category: "Mobility" }
      ]
    }
  ],
  endurance: [
    {
      day: "Day 1",
      name: "Aerobic Capacity Building",
      exercises: [
        { name: "Steady-state Jogging", sets: 1, reps: "30 min", rest: "None", category: "Cardio" },
        { name: "Jump Rope Rounds", sets: 5, reps: "2 min", rest: "45 sec", category: "Cardio" },
        { name: "Bodyweight Squats (High Reps)", sets: 3, reps: "30 reps", rest: "30 sec", category: "Endurance" },
        { name: "Plank-to-Pushup transitions", sets: 3, reps: "15 reps", rest: "45 sec", category: "Endurance" }
      ]
    },
    {
      day: "Day 2",
      name: "Stamina & Muscular Endurance",
      exercises: [
        { name: "Kettlebell Swing Circuit", sets: 4, reps: "30 reps", rest: "30 sec", category: "Endurance" },
        { name: "Dumbbell Thrusters (Light)", sets: 4, reps: "20 reps", rest: "30 sec", category: "Endurance" },
        { name: "Mountain Climbers (Fast)", sets: 4, reps: "60 sec", rest: "20 sec", category: "Cardio" },
        { name: "Walking Lunges (High Rep)", sets: 3, reps: "20 per leg", rest: "30 sec", category: "Endurance" },
        { name: "Hollow Body Rock Hold", sets: 3, reps: "45 sec", rest: "30 sec", category: "Core" }
      ]
    },
    {
      day: "Day 3",
      name: "Speed Endurance & Agility",
      exercises: [
        { name: "Shuttle Runs (Suicides)", sets: 5, reps: "30 sec sprints", rest: "60 sec", category: "Cardio" },
        { name: "Burpees (Continuous)", sets: 3, reps: "15 reps", rest: "30 sec", category: "Cardio" },
        { name: "Bicycle Crunches (High Tempo)", sets: 3, reps: "40 reps", rest: "20 sec", category: "Core" },
        { name: "High Knees Sprinting", sets: 4, reps: "45 sec", rest: "15 sec", category: "Cardio" }
      ]
    }
  ]
};

function generateWorkoutRoutine(goal) {
  // Returns workout template based on goals, or uses active_lifestyle as fallback
  const routine = WORKOUT_TEMPLATES[goal] || WORKOUT_TEMPLATES.active_lifestyle;
  return routine;
}


// --- AI MEAL SCANNER RECOGNITION SYSTEM ---

// Preset database matching food properties
const FOOD_DATABASE = {
  salad: {
    name: "Grilled Chicken Caesar Salad",
    calories: 480,
    protein: 34,
    carbs: 16,
    fats: 28,
    healthScore: "B",
    matchLabel: "Caesar Salad",
    alternatives: [
      { from: "High calorie creamy dressing", to: "Lemon Herb Greek Yogurt Dressing (Saves 180 kcal)" },
      { from: "White flour croutons", to: "Baked pumpkin seeds or toasted chickpeas (More protein & fiber)" }
    ]
  },
  burger: {
    name: "Double Cheeseburger & French Fries",
    calories: 1120,
    protein: 48,
    carbs: 115,
    fats: 52,
    healthScore: "D",
    matchLabel: "Cheeseburger Meal",
    alternatives: [
      { from: "Deep fried French fries", to: "Spiced air-fried sweet potato wedges (Saves 200 kcal, higher Vitamin A)" },
      { from: "Double beef patties & cheese slices", to: "Grilled chicken breast burger on whole-grain wrap (Saves 450 kcal)" }
    ]
  },
  salmon: {
    name: "Teriyaki Salmon and Red Quinoa Bowl",
    calories: 620,
    protein: 38,
    carbs: 48,
    fats: 24,
    healthScore: "A",
    matchLabel: "Salmon Quinoa Bowl",
    alternatives: [
      { from: "High sugar teriyaki glaze", to: "Light soy-ginger dressing & sesame oil drizzle (Saves 80 kcal)" }
    ]
  },
  pizza: {
    name: "Pepperoni & Cheese Pizza (2 slices)",
    calories: 590,
    protein: 24,
    carbs: 64,
    fats: 25,
    healthScore: "C",
    matchLabel: "Pepperoni Pizza",
    alternatives: [
      { from: "Refined wheat flour crust", to: "Cauliflower crust or whole-grain thin crust (More fiber, lower glycemic load)" },
      { from: "Heavy pepperoni meat", to: "Grilled bell peppers, onions, & shredded chicken breast topping (Saves 120 kcal)" }
    ]
  },
  toast: {
    name: "Avocado Sourdough Toast with Poached Egg",
    calories: 360,
    protein: 15,
    carbs: 38,
    fats: 16,
    healthScore: "A",
    matchLabel: "Avocado Toast",
    alternatives: [
      { from: "Butter spread on toast base", to: "Hold the butter; avocado provides plenty of healthy fats (Saves 80 kcal)" }
    ]
  },
  fallback: {
    name: "Mediterranean Protein Power Bowl",
    calories: 540,
    protein: 32,
    carbs: 45,
    fats: 18,
    healthScore: "A",
    matchLabel: "Healthy Grain Bowl",
    alternatives: [
      { from: "White rice bed", to: "Warm brown rice or tri-color quinoa (More fiber, fuller longer)" }
    ]
  }
};

// Simulation scanning logic
function scanMealImage(filename, callback) {
  // Guess the food based on the filename/metadata keywords
  const fileLower = (filename || "").toLowerCase();
  let foodKey = 'fallback';

  if (fileLower.includes('salad') || fileLower.includes('caesar') || fileLower.includes('green')) {
    foodKey = 'salad';
  } else if (fileLower.includes('burger') || fileLower.includes('fry') || fileLower.includes('fries') || fileLower.includes('beef') || fileLower.includes('junk')) {
    foodKey = 'burger';
  } else if (fileLower.includes('salmon') || fileLower.includes('fish') || fileLower.includes('quinoa') || fileLower.includes('teriyaki')) {
    foodKey = 'salmon';
  } else if (fileLower.includes('pizza') || fileLower.includes('pepperoni') || fileLower.includes('slice')) {
    foodKey = 'pizza';
  } else if (fileLower.includes('toast') || fileLower.includes('avocado') || fileLower.includes('egg')) {
    foodKey = 'toast';
  } else {
    // Random select logic from presets for cool generic results if no keyword
    const keys = ['salad', 'burger', 'salmon', 'pizza', 'toast'];
    foodKey = keys[Math.floor(Math.random() * keys.length)];
  }

  const result = FOOD_DATABASE[foodKey];
  
  // Phase loading simulation
  const statuses = [
    "Analyzing image structure...",
    "Running computer vision models...",
    "Segmenting food items...",
    "Detecting nutritional characteristics...",
    "Querying HealthVerse AI knowledge..."
  ];

  let currentStep = 0;
  
  const timer = setInterval(() => {
    if (currentStep < statuses.length) {
      if (typeof callback.onProgress === 'function') {
        callback.onProgress(statuses[currentStep]);
      }
      currentStep++;
    } else {
      clearInterval(timer);
      if (typeof callback.onComplete === 'function') {
        callback.onComplete(result);
      }
    }
  }, 500); // 2.5 seconds total
}


// --- ACTIVE WORKOUT CONTROLLER ---

let workoutTimerInterval = null;
let workoutSeconds = 0;

function startWorkoutTimer(onTick) {
  workoutSeconds = 0;
  if (workoutTimerInterval) clearInterval(workoutTimerInterval);
  workoutTimerInterval = setInterval(() => {
    workoutSeconds++;
    const hours = Math.floor(workoutSeconds / 3600);
    const minutes = Math.floor((workoutSeconds % 3600) / 60);
    const secs = workoutSeconds % 60;
    const formatted = [
      hours > 0 ? String(hours).padStart(2, '0') : null,
      String(minutes).padStart(2, '0'),
      String(secs).padStart(2, '0')
    ].filter(Boolean).join(':');
    
    if (typeof onTick === 'function') {
      onTick(formatted);
    }
  }, 1000);
}

function stopWorkoutTimer() {
  if (workoutTimerInterval) {
    clearInterval(workoutTimerInterval);
    workoutTimerInterval = null;
  }
  return Math.ceil(workoutSeconds / 60); // Return duration in minutes
}


// --- CHARTS VISUALIZATION BINDINGS (CHART.JS) ---

let weightChartInstance = null;
let calorieChartInstance = null;

function renderCharts() {
  const ctxWeight = document.getElementById('weightHistoryChart');
  const ctxCalorie = document.getElementById('calorieHistoryChart');

  if (!ctxWeight || !ctxCalorie) return;

  // Destruct existing instances
  if (weightChartInstance) weightChartInstance.destroy();
  if (calorieChartInstance) calorieChartInstance.destroy();

  // Sort weight logs by date
  const sortedWeightLogs = [...appState.weightLogs].sort((a, b) => new Date(a.date) - new Date(b.date));
  const weightLabels = sortedWeightLogs.map(l => {
    const d = new Date(l.date);
    return d.toLocaleDateString(undefined, { month: 'short', day: 'numeric' });
  });
  const weightData = sortedWeightLogs.map(l => l.weight);

  const isDark = appState.theme === 'dark';
  const gridColor = isDark ? 'rgba(255, 255, 255, 0.05)' : 'rgba(0, 0, 0, 0.05)';
  const textColor = isDark ? '#9ca3af' : '#64748b';
  const legendColor = isDark ? '#f4f4f5' : '#1e293b';

  // Weight Trend Line Chart
  weightChartInstance = new Chart(ctxWeight, {
    type: 'line',
    data: {
      labels: weightLabels.length ? weightLabels : ["No logs"],
      datasets: [{
        label: 'Weight (kg)',
        data: weightData.length ? weightData : [0],
        borderColor: isDark ? '#06b6d4' : '#0d9488',
        backgroundColor: isDark ? 'rgba(6, 182, 212, 0.15)' : 'rgba(13, 148, 136, 0.1)',
        borderWidth: 3,
        fill: true,
        tension: 0.4,
        pointBackgroundColor: isDark ? '#8b5cf6' : '#4f46e5',
        pointHoverRadius: 7
      }]
    },
    options: {
      responsive: true,
      maintainAspectRatio: false,
      plugins: {
        legend: { display: false }
      },
      scales: {
        y: {
          grid: { color: gridColor },
          ticks: { color: textColor }
        },
        x: {
          grid: { display: false },
          ticks: { color: textColor }
        }
      }
    }
  });

  // Calculate past 7 days calories logs vs goal line
  const now = new Date();
  const pastDaysLabels = [];
  const calorieIntakes = [];
  const targetCaloriesArray = [];
  const dailyTarget = appState.profile ? appState.profile.metrics.targetCalories : 2000;

  for (let i = 6; i >= 0; i--) {
    const d = new Date();
    d.setDate(now.getDate() - i);
    const dayName = d.toLocaleDateString(undefined, { weekday: 'short' });
    pastDaysLabels.push(dayName);

    // Sum matching meals for that historical day. Since it's mockup, we generate realistic values
    // if there are no logged meals in historical records.
    let dailySum = 0;
    const dateStr = d.toDateString();
    
    if (dateStr === now.toDateString()) {
      dailySum = appState.dailyIntake.calories;
    } else {
      // Return a seeded pseudo random calorie total that centers around targets for realistic visual layout
      const seedVal = Math.sin(d.getDate()) * 200;
      dailySum = Math.round(dailyTarget * 0.9 + seedVal);
    }
    calorieIntakes.push(dailySum);
    targetCaloriesArray.push(dailyTarget);
  }

  // Calorie History Bar Chart
  calorieChartInstance = new Chart(ctxCalorie, {
    type: 'bar',
    data: {
      labels: pastDaysLabels,
      datasets: [
        {
          label: 'Calories Consumed',
          data: calorieIntakes,
          backgroundColor: isDark ? '#8b5cf6' : '#4f46e5',
          borderRadius: 6,
          barThickness: 16
        },
        {
          label: 'Target Limit',
          data: targetCaloriesArray,
          type: 'line',
          borderColor: '#ec4899',
          borderWidth: 2,
          borderDash: [5, 5],
          fill: false,
          pointStyle: 'none',
          pointRadius: 0
        }
      ]
    },
    options: {
      responsive: true,
      maintainAspectRatio: false,
      plugins: {
        legend: {
          labels: { color: legendColor }
        }
      },
      scales: {
        y: {
          grid: { color: gridColor },
          ticks: { color: textColor }
        },
        x: {
          grid: { display: false },
          ticks: { color: textColor }
        }
      }
    }
  });
}


// --- VIEW ROUTING & INITIALIZATION ---

function setupNavigation() {
  const navLinks = document.querySelectorAll('.nav-links .nav-item a, .mobile-nav-links .mobile-nav-item a');
  
  navLinks.forEach(link => {
    link.addEventListener('click', function(e) {
      e.preventDefault();
      
      const targetId = this.getAttribute('href').substring(1);
      
      // If profile is not set and attempting to visit pages other than onboarding
      if (!appState.profile && targetId !== 'profile-panel') {
        alert("Please set up your AI Fitness Profile first to unlock HealthVerse AI!");
        switchView('profile-panel');
        return;
      }

      switchView(targetId);
    });
  });
}

function switchView(panelId) {
  // Hide all panels
  document.querySelectorAll('.view-panel').forEach(p => p.classList.remove('active'));
  
  // Show target panel
  const targetPanel = document.getElementById(panelId);
  if (targetPanel) {
    targetPanel.classList.add('active');
  }

  // Update navigation styles
  const cleanPanelId = `#${panelId}`;
  
  document.querySelectorAll('.nav-links .nav-item, .mobile-nav-links .mobile-nav-item').forEach(item => {
    const link = item.querySelector('a');
    if (link && link.getAttribute('href') === cleanPanelId) {
      item.classList.add('active');
    } else {
      item.classList.remove('active');
    }
  });

  // Re-render charts if analytics view is active
  if (panelId === 'analytics-panel') {
    setTimeout(renderCharts, 50); // Small timeout to ensure DOM dimensions are set
  }
}

// Update DOM elements on dashboard & sidebar based on current state
function updateUI() {
  // 1. Check Profile
  const profileSection = document.getElementById('profile-panel');
  const userSetupTip = document.getElementById('dashboard-setup-tip');
  const dashboardStats = document.getElementById('dashboard-stats-grid');
  
  if (appState.profile) {
    // Set user badges
    document.querySelectorAll('.user-name').forEach(el => el.textContent = appState.profile.name);
    
    let goalLabel = "Active Lifestyle";
    if (appState.profile.goal === 'lose_fat') goalLabel = "Lose Fat";
    else if (appState.profile.goal === 'gain_muscle') goalLabel = "Build Muscle";
    else if (appState.profile.goal === 'endurance') goalLabel = "Endurance Run";
    document.querySelectorAll('.user-goal-tag').forEach(el => el.textContent = goalLabel);

    // Hide onboarding instruction banner, show stat widgets
    if (userSetupTip) userSetupTip.style.display = 'none';
    if (dashboardStats) dashboardStats.style.display = 'grid';

    // Set Dashboard Stats
    const metrics = appState.profile.metrics;
    document.getElementById('dash-weight-val').textContent = `${appState.profile.weight} kg`;
    document.getElementById('dash-bmi-val').textContent = metrics.bmi;
    document.getElementById('dash-tdee-val').textContent = `${metrics.tdee} kcal`;
    
    // Nutrition ring calculations
    const caloriesPercentage = Math.min((appState.dailyIntake.calories / metrics.targetCalories) * 100, 100);
    const circle = document.getElementById('dash-calories-circle-progress');
    if (circle) {
      // Stroke-dasharray is 440. Calculate offset
      const offset = 440 - (440 * caloriesPercentage) / 100;
      circle.style.strokeDashoffset = offset;
    }
    
    document.getElementById('dash-calories-consumed').textContent = appState.dailyIntake.calories;
    document.getElementById('dash-calories-target').textContent = metrics.targetCalories;

    // Macro progress bars
    updateMacroBar('protein', appState.dailyIntake.protein, metrics.targetProtein);
    updateMacroBar('carbs', appState.dailyIntake.carbs, metrics.targetCarbs);
    updateMacroBar('fats', appState.dailyIntake.fats, metrics.targetFats);

    // Dynamic workouts routine container
    renderWorkoutRoutineUI();
  } else {
    // No profile, show onboarding prompt
    document.querySelectorAll('.user-name').forEach(el => el.textContent = "Guest User");
    document.querySelectorAll('.user-goal-tag').forEach(el => el.textContent = "Setup Profile");
    if (userSetupTip) userSetupTip.style.display = 'block';
    if (dashboardStats) dashboardStats.style.display = 'none';
  }

  // Logs list on analytics panel
  renderLogsUI();
}

function updateMacroBar(macro, consumed, target) {
  const pct = Math.min((consumed / target) * 100, 100);
  const textEl = document.getElementById(`dash-${macro}-val`);
  const progressEl = document.getElementById(`dash-${macro}-progress`);
  
  if (textEl) textEl.textContent = `${consumed}g / ${target}g`;
  if (progressEl) progressEl.style.width = `${pct}%`;
}

function renderWorkoutRoutineUI() {
  const container = document.getElementById('routine-days-tabs');
  const routineDetails = document.getElementById('routine-details-container');
  if (!container || !routineDetails) return;

  if (!appState.customRoutine) {
    appState.customRoutine = generateWorkoutRoutine(appState.profile.goal);
    saveState();
  }

  // Render day buttons
  container.innerHTML = '';
  appState.customRoutine.forEach((day, index) => {
    const btn = document.createElement('button');
    btn.className = `day-tab-btn ${index === 0 ? 'active' : ''}`;
    btn.textContent = `${day.day}: ${day.name}`;
    btn.addEventListener('click', () => {
      document.querySelectorAll('.day-tab-btn').forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
      renderSelectedDayWorkout(day);
    });
    container.appendChild(btn);
  });

  // Render initial day
  renderSelectedDayWorkout(appState.customRoutine[0]);
}

function renderSelectedDayWorkout(dayData) {
  const detailsContainer = document.getElementById('routine-details-container');
  if (!detailsContainer) return;

  let exercisesHtml = '';
  dayData.exercises.forEach(ex => {
    exercisesHtml += `
      <div class="exercise-item">
        <div class="exercise-details">
          <span class="exercise-name">${ex.name}</span>
          <div class="exercise-badges">
            <span class="badge badge-blue">${ex.category}</span>
            <span class="badge badge-purple">Rest: ${ex.rest}</span>
          </div>
        </div>
        <span class="exercise-sets-rep">${ex.sets} sets × ${ex.reps}</span>
      </div>
    `;
  });

  detailsContainer.innerHTML = `
    <div class="glass-card" style="margin-bottom: 0;">
      <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:1.5rem; flex-wrap:wrap; gap: 1rem;">
        <div>
          <h3 style="font-size:1.4rem; color:white;">${dayData.name}</h3>
          <p style="color:var(--color-text-muted); font-size:0.85rem; margin-top:0.15rem;">Customized AI routine mapped to your goal.</p>
        </div>
        <button id="start-workout-btn" class="btn btn-teal">
          <i data-lucide="play"></i> Start Workout
        </button>
      </div>
      <div class="exercises-list">
        ${exercisesHtml}
      </div>
    </div>
  `;

  // Attach start workout listener
  document.getElementById('start-workout-btn').addEventListener('click', () => {
    launchActiveWorkout(dayData);
  });
}

function renderLogsUI() {
  const mealContainer = document.getElementById('meals-log-list');
  const workoutContainer = document.getElementById('workouts-log-list');

  if (mealContainer) {
    if (appState.meals.length === 0) {
      mealContainer.innerHTML = `<div style="text-align:center; padding:1.5rem; color:var(--color-text-muted); font-size:0.85rem;">No meals logged today.</div>`;
    } else {
      mealContainer.innerHTML = appState.meals.slice().reverse().map(meal => `
        <div class="log-item">
          <div>
            <div class="log-title">${meal.name}</div>
            <div class="log-date">${new Date(meal.timestamp).toLocaleTimeString(undefined, { hour: '2-digit', minute: '2-digit' })}</div>
          </div>
          <div class="log-value calories">+${meal.calories} kcal</div>
        </div>
      `).join('');
    }
  }

  if (workoutContainer) {
    if (appState.workouts.length === 0) {
      workoutContainer.innerHTML = `<div style="text-align:center; padding:1.5rem; color:var(--color-text-muted); font-size:0.85rem;">No workouts completed yet.</div>`;
    } else {
      workoutContainer.innerHTML = appState.workouts.slice().reverse().map(w => `
        <div class="log-item">
          <div>
            <div class="log-title">${w.title}</div>
            <div class="log-date">${new Date(w.timestamp).toLocaleDateString()} at ${new Date(w.timestamp).toLocaleTimeString(undefined, { hour: '2-digit', minute: '2-digit' })}</div>
          </div>
          <div class="log-value workout">${w.durationMinutes} mins</div>
        </div>
      `).join('');
    }
  }
}

// Active workout overlay launcher
function launchActiveWorkout(dayData) {
  const overlay = document.getElementById('active-workout-panel');
  const timerLabel = document.getElementById('active-timer-label');
  const titleEl = document.getElementById('active-workout-title');
  const exercisesContainer = document.getElementById('active-exercises-list');

  if (!overlay || !timerLabel || !titleEl || !exercisesContainer) return;

  appState.activeWorkout = {
    title: dayData.name,
    exercises: dayData.exercises.map(ex => ({ ...ex, completed: false })),
    startTime: new Date().toISOString()
  };

  titleEl.textContent = dayData.name;
  overlay.classList.add('active');

  // Load exercises list
  renderActiveExercises();

  // Start stopwatch
  startWorkoutTimer((formattedTime) => {
    timerLabel.textContent = formattedTime;
  });

  // Event handlers for action buttons
  const quitBtn = document.getElementById('active-quit-btn');
  const completeBtn = document.getElementById('active-complete-btn');

  // Single-use actions to prevent duplicates
  quitBtn.onclick = () => {
    if (confirm("Are you sure you want to stop the workout? Progress will not be saved.")) {
      stopWorkoutTimer();
      appState.activeWorkout = null;
      overlay.classList.remove('active');
    }
  };

  completeBtn.onclick = () => {
    const mins = stopWorkoutTimer();
    const exCount = appState.activeWorkout.exercises.filter(ex => ex.completed).length;
    
    // Add to completed list
    appState.workouts.push({
      title: appState.activeWorkout.title,
      exercisesCount: exCount,
      durationMinutes: mins,
      timestamp: new Date().toISOString()
    });

    overlay.classList.remove('active');
    appState.activeWorkout = null;
    saveState();
    updateUI();

    // Trigger celebration dialog modal
    showCongratsModal(mins, exCount);
  };
}

function renderActiveExercises() {
  const exercisesContainer = document.getElementById('active-exercises-list');
  if (!exercisesContainer) return;

  exercisesContainer.innerHTML = '';
  appState.activeWorkout.exercises.forEach((ex, idx) => {
    const card = document.createElement('div');
    card.className = `active-exercise-card ${ex.completed ? 'completed' : ''}`;
    card.innerHTML = `
      <div class="exercise-details">
        <span class="active-ex-name" style="font-weight:600; font-size:1.05rem; color:#fff;">${ex.name}</span>
        <span style="font-size:0.8rem; color:var(--color-text-muted); margin-top:0.25rem;">Sets/Reps: ${ex.sets} × ${ex.reps} | Rest: ${ex.rest}</span>
      </div>
      <button class="checkbox-btn">
        <i data-lucide="check" style="${ex.completed ? 'opacity:1' : 'opacity:0'}"></i>
      </button>
    `;

    // Toggle exercise completion
    card.querySelector('.checkbox-btn').onclick = () => {
      ex.completed = !ex.completed;
      card.classList.toggle('completed', ex.completed);
      card.querySelector('.checkbox-btn i').style.opacity = ex.completed ? 1 : 0;
      saveState();
    };

    exercisesContainer.appendChild(card);
  });
}

function showCongratsModal(minutes, exerciseCount) {
  const body = document.body;
  const overlay = document.createElement('div');
  overlay.className = 'modal-backdrop';
  overlay.id = 'congrats-modal-backdrop';

  overlay.innerHTML = `
    <div class="glass-card congrats-modal">
      <div style="font-size: 3.5rem; margin-bottom: 1rem;">🎉</div>
      <h3 style="font-size: 1.8rem; font-weight:800; background: linear-gradient(135deg, var(--color-secondary), var(--color-primary)); -webkit-background-clip:text; -webkit-text-fill-color:transparent; margin-bottom: 0.5rem;">Workout Complete!</h3>
      <p style="color:var(--color-text-muted); margin-bottom: 1.5rem;">You smashed today's routine like a champion!</p>
      
      <div style="display:flex; justify-content:space-around; width:100%; margin-bottom: 1.5rem; background:rgba(255,255,255,0.02); padding: 1rem; border-radius:12px;">
        <div>
          <div style="font-size:1.3rem; font-weight:700; color:var(--color-secondary);">${minutes}</div>
          <div style="font-size:0.75rem; color:var(--color-text-muted); text-transform:uppercase;">Minutes</div>
        </div>
        <div style="border-right: 1px solid rgba(255,255,255,0.05);"></div>
        <div>
          <div style="font-size:1.3rem; font-weight:700; color:var(--color-accent);">${exerciseCount}</div>
          <div style="font-size:0.75rem; color:var(--color-text-muted); text-transform:uppercase;">Exercises</div>
        </div>
      </div>

      <button id="congrats-dismiss-btn" class="btn btn-primary" style="width:100%;">Back to Dashboard</button>
    </div>
  `;

  body.appendChild(overlay);

  document.getElementById('congrats-dismiss-btn').onclick = () => {
    overlay.remove();
    switchView('dashboard-panel');
  };
}


// --- MEAL SCANNER INTERACTION MANAGEMENT ---

function initMealScanner() {
  const dropZone = document.getElementById('scanner-dropzone');
  const fileInput = document.getElementById('scanner-file-input');
  const actionContainer = document.getElementById('scanner-action-container');
  const resultCard = document.getElementById('scanner-results-card');
  const chipContainer = document.getElementById('scanner-preset-chips');

  if (!dropZone || !fileInput || !actionContainer || !resultCard) return;

  // Handle preset chips click
  if (chipContainer) {
    chipContainer.querySelectorAll('.preset-chip').forEach(chip => {
      chip.addEventListener('click', () => {
        const foodType = chip.getAttribute('data-food');
        
        // Setup a mock scanned state
        showScannedPreview(`images/presets/${foodType}.png`, `${foodType}_preset_meal.png`);
      });
    });
  }

  // Trigger file dialog
  dropZone.addEventListener('click', (e) => {
    if (e.target.closest('#scanner-remove-preview-btn') || e.target.closest('.btn')) {
      return; // Ignore if clicking remove/action buttons
    }
    fileInput.click();
  });

  // Drag over / leave styling
  dropZone.addEventListener('dragover', (e) => {
    e.preventDefault();
    dropZone.classList.add('dragover');
  });

  dropZone.addEventListener('dragleave', () => {
    dropZone.classList.remove('dragover');
  });

  dropZone.addEventListener('drop', (e) => {
    e.preventDefault();
    dropZone.classList.remove('dragover');
    
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      handleUploadedFile(e.dataTransfer.files[0]);
    }
  });

  fileInput.addEventListener('change', () => {
    if (fileInput.files && fileInput.files[0]) {
      handleUploadedFile(fileInput.files[0]);
    }
  });
}

function handleUploadedFile(file) {
  const reader = new FileReader();
  reader.onload = (e) => {
    showScannedPreview(e.target.result, file.name);
  };
  reader.readAsDataURL(file);
}

function showScannedPreview(imageSrc, fileName) {
  const dropZone = document.getElementById('scanner-dropzone');
  const actionContainer = document.getElementById('scanner-action-container');
  const resultCard = document.getElementById('scanner-results-card');

  // Replace drop zone display with image preview
  dropZone.innerHTML = `
    <div style="position:relative; display:inline-block; max-width:100%;">
      <img src="${imageSrc}" class="preview-image" id="uploaded-meal-img" alt="Meal Preview">
      <button id="scanner-remove-preview-btn" style="position:absolute; top:-10px; right:-10px; background:var(--color-danger); color:white; border:none; width:26px; height:26px; border-radius:50%; cursor:pointer; display:flex; align-items:center; justify-content:center; font-size:0.9rem; box-shadow:0 2px 8px rgba(0,0,0,0.3);"><i data-lucide="x"></i></button>
    </div>
    <div style="font-size:0.8rem; color:var(--color-text-muted); margin-top:0.5rem; word-break:break-all;">Uploaded: ${fileName}</div>
  `;

  // Repaint icon triggers
  lucide.createIcons();

  // Attach delete preview action
  document.getElementById('scanner-remove-preview-btn').onclick = (e) => {
    e.stopPropagation();
    resetScannerUI();
  };

  // Prepare Actions section
  actionContainer.style.display = 'block';
  actionContainer.innerHTML = `
    <button id="scanner-analyze-btn" class="btn btn-primary" style="width: 100%;">
      <i data-lucide="scan"></i> Run AI Nutrition Scan
    </button>
  `;

  // Hide older results if present
  resultCard.style.display = 'none';

  // Attach Analysis action
  document.getElementById('scanner-analyze-btn').onclick = () => {
    triggerAIScanAnimation(fileName, imageSrc);
  };
}

function resetScannerUI() {
  const dropZone = document.getElementById('scanner-dropzone');
  const actionContainer = document.getElementById('scanner-action-container');
  const resultCard = document.getElementById('scanner-results-card');
  const fileInput = document.getElementById('scanner-file-input');

  if (fileInput) fileInput.value = '';

  dropZone.innerHTML = `
    <div class="upload-icon">
      <i data-lucide="upload-cloud"></i>
    </div>
    <div>
      <div class="upload-zone-title">Upload a picture of your meal</div>
      <div class="upload-zone-text">Drag & drop here, or click to browse files</div>
    </div>
    <div style="font-size:0.75rem; color:var(--color-text-muted);">Supports PNG, JPG, or JPEG formats. Or click presets below.</div>
  `;

  lucide.createIcons();

  actionContainer.style.display = 'none';
  actionContainer.innerHTML = '';
  resultCard.style.display = 'none';
}

function triggerAIScanAnimation(fileName, imageSrc) {
  const dropZone = document.getElementById('scanner-dropzone');
  const actionContainer = document.getElementById('scanner-action-container');
  const resultCard = document.getElementById('scanner-results-card');

  // Insert scanning graphics overlay
  dropZone.innerHTML = `
    <div class="scan-animation-container">
      <img src="${imageSrc}" class="preview-image" style="opacity: 0.85; filter: grayscale(30%);" alt="Meal Preview">
      <div class="scan-laser"></div>
      <div class="scanning-overlay-blur"></div>
    </div>
    <div id="scanner-progress-lbl" style="font-size:0.9rem; font-weight:600; color:var(--color-secondary); margin-top:0.75rem; display:flex; align-items:center; gap:0.5rem; justify-content:center;">
      <span class="scanning-spinner"></span> Initializing neural scans...
    </div>
  `;

  // Hide trigger buttons during scan
  actionContainer.innerHTML = `
    <button class="btn btn-secondary" style="width: 100%;" disabled>
      AI Scanner Processing...
    </button>
  `;

  scanMealImage(fileName, {
    onProgress: (statusText) => {
      const lbl = document.getElementById('scanner-progress-lbl');
      if (lbl) {
        lbl.innerHTML = `<span class="scanning-spinner"></span> ${statusText}`;
      }
    },
    onComplete: (foodData) => {
      // Completed scanning! Display results
      displayScannerResults(foodData, imageSrc, fileName);
    }
  });
}

function displayScannerResults(foodData, imageSrc, fileName) {
  // Restore image preview in dropZone without scan effects
  const dropZone = document.getElementById('scanner-dropzone');
  const actionContainer = document.getElementById('scanner-action-container');
  const resultCard = document.getElementById('scanner-results-card');

  dropZone.innerHTML = `
    <div style="position:relative; display:inline-block; max-width:100%;">
      <img src="${imageSrc}" class="preview-image" alt="Meal Preview">
    </div>
    <div style="font-size:0.8rem; color:var(--color-text-muted); margin-top:0.5rem;">Scanned: ${fileName}</div>
  `;

  // Show result details card
  resultCard.style.display = 'block';
  document.getElementById('res-food-name').textContent = foodData.name;
  
  // Health Score Tag Styling
  const badge = document.getElementById('res-health-score');
  badge.className = `health-score-badge ${foodData.healthScore}`;
  badge.innerHTML = `Health Score: <strong>${foodData.healthScore}</strong>`;

  // Micro donut counts
  document.getElementById('res-cal').textContent = `${foodData.calories} kcal`;
  document.getElementById('res-protein').textContent = `${foodData.protein}g`;
  document.getElementById('res-carbs').textContent = `${foodData.carbs}g`;
  document.getElementById('res-fats').textContent = `${foodData.fats}g`;

  // Render macro percentage subtext
  const totalGrams = foodData.protein + foodData.carbs + foodData.fats;
  document.getElementById('res-protein-pct').textContent = Math.round((foodData.protein / totalGrams) * 100) + '%';
  document.getElementById('res-carbs-pct').textContent = Math.round((foodData.carbs / totalGrams) * 100) + '%';
  document.getElementById('res-fats-pct').textContent = Math.round((foodData.fats / totalGrams) * 100) + '%';

  // Render healthy alternatives
  const swapContainer = document.getElementById('res-swaps-list');
  if (foodData.alternatives && foodData.alternatives.length > 0) {
    swapContainer.innerHTML = foodData.alternatives.map(alt => `
      <div class="swap-item">
        <div>
          <div class="swap-from">${alt.from}</div>
          <div class="swap-to"><i data-lucide="chevron-right" style="font-size:0.8rem; color:var(--color-success)"></i> ${alt.to}</div>
        </div>
      </div>
    `).join('');
  } else {
    swapContainer.innerHTML = `<div style="font-size:0.85rem; color:var(--color-success); font-weight:600;"><i data-lucide="check-circle"></i> Outstanding choice! No food swaps needed for this meal.</div>`;
  }

  // Action actions
  actionContainer.innerHTML = `
    <div style="display:grid; grid-template-columns: 1fr 1fr; gap: 0.75rem; width:100%;">
      <button id="scanner-log-meal-btn" class="btn btn-accent">
        <i data-lucide="check"></i> Log to Dashboard
      </button>
      <button id="scanner-reset-btn" class="btn btn-secondary">
        Scan Another
      </button>
    </div>
  `;

  // Repaint icon triggers
  lucide.createIcons();

  // Button actions handlers
  document.getElementById('scanner-reset-btn').onclick = resetScannerUI;
  
  document.getElementById('scanner-log-meal-btn').onclick = () => {
    // Add calories to daily totals
    appState.dailyIntake.calories += foodData.calories;
    appState.dailyIntake.protein += foodData.protein;
    appState.dailyIntake.carbs += foodData.carbs;
    appState.dailyIntake.fats += foodData.fats;

    // Log meal entries
    appState.meals.push({
      name: foodData.name,
      calories: foodData.calories,
      protein: foodData.protein,
      carbs: foodData.carbs,
      fats: foodData.fats,
      timestamp: new Date().toISOString()
    });

    saveState();
    updateUI();
    
    alert(`Successfully logged ${foodData.name} (${foodData.calories} kcal) to your dashboard!`);
    resetScannerUI();
    switchView('dashboard-panel');
  };
}


// --- PROFILE SETUP FORM ONBOARDING WIZARD ---

function initOnboardingWizard() {
  const wizard = document.getElementById('profile-wizard');
  if (!wizard) return;

  const steps = wizard.querySelectorAll('.wizard-step');
  const progressBar = document.getElementById('wizard-progress-bar');
  const prevBtn = document.getElementById('wizard-prev-btn');
  const nextBtn = document.getElementById('wizard-next-btn');

  let currentStep = 0;

  // Single choice options selection togglers (Gender, Activity, Goals)
  const optionSelect = (parentSelector, stateField) => {
    const parent = wizard.querySelector(parentSelector);
    if (!parent) return;

    parent.querySelectorAll('.wizard-option-card').forEach(card => {
      card.addEventListener('click', function() {
        parent.querySelectorAll('.wizard-option-card').forEach(c => c.classList.remove('selected'));
        this.classList.add('selected');
        
        const val = this.getAttribute('data-value');
        wizard.setAttribute(`data-${stateField}`, val);
      });
    });
  };

  optionSelect('.gender-select-container', 'gender');
  optionSelect('.activity-select-container', 'activity');
  optionSelect('.goal-select-container', 'goal');

  // Prepopulate if state exists
  if (appState.profile) {
    document.getElementById('p-name').value = appState.profile.name || '';
    document.getElementById('p-age').value = appState.profile.age || '';
    document.getElementById('p-height').value = appState.profile.height || '';
    document.getElementById('p-weight').value = appState.profile.weight || '';

    // Mark selected cards
    setCardPreSelected('.gender-select-container', 'gender', appState.profile.gender);
    setCardPreSelected('.activity-select-container', 'activity', appState.profile.activityLevel);
    setCardPreSelected('.goal-select-container', 'goal', appState.profile.goal);

    // Precalculate BMI / TDEE panel metrics
    displayProfileSummary();
  }

  function setCardPreSelected(parentSelector, attrName, value) {
    const parent = wizard.querySelector(parentSelector);
    if (!parent || !value) return;
    
    wizard.setAttribute(`data-${attrName}`, value);
    parent.querySelectorAll('.wizard-option-card').forEach(card => {
      if (card.getAttribute('data-value') === value) {
        card.classList.add('selected');
      } else {
        card.classList.remove('selected');
      }
    });
  }

  function updateWizardState() {
    steps.forEach((step, idx) => {
      step.classList.toggle('active', idx === currentStep);
    });

    // Progress bar width
    const pct = ((currentStep + 1) / steps.length) * 100;
    progressBar.style.width = `${pct}%`;

    // Button states
    prevBtn.disabled = currentStep === 0;

    if (currentStep === steps.length - 1) {
      nextBtn.innerHTML = `<i data-lucide="check"></i> Complete Profile`;
    } else {
      nextBtn.innerHTML = `Next Step <i data-lucide="arrow-right"></i>`;
    }
    
    // Repaint icons
    lucide.createIcons();
  }

  prevBtn.onclick = () => {
    if (currentStep > 0) {
      currentStep--;
      updateWizardState();
    }
  };

  nextBtn.onclick = () => {
    // Step validation
    if (currentStep === 0) {
      const name = document.getElementById('p-name').value.trim();
      const age = parseInt(document.getElementById('p-age').value);
      const height = parseFloat(document.getElementById('p-height').value);
      const weight = parseFloat(document.getElementById('p-weight').value);
      const gender = wizard.getAttribute('data-gender');

      if (!name || isNaN(age) || isNaN(height) || isNaN(weight) || !gender) {
        alert("Please fill out all physical metrics and select a biological gender.");
        return;
      }
    } else if (currentStep === 1) {
      const activity = wizard.getAttribute('data-activity');
      const goal = wizard.getAttribute('data-goal');

      if (!activity || !goal) {
        alert("Please select both your physical activity level and primary fitness goal.");
        return;
      }

      // Pre-calculate profile results before showing Summary step
      const name = document.getElementById('p-name').value.trim();
      const age = parseInt(document.getElementById('p-age').value);
      const height = parseFloat(document.getElementById('p-height').value);
      const weight = parseFloat(document.getElementById('p-weight').value);
      const gender = wizard.getAttribute('data-gender');
      const activityVal = wizard.getAttribute('data-activity');
      const goalVal = wizard.getAttribute('data-goal');

      const metrics = calculateMetrics(age, gender, height, weight, activityVal, goalVal);

      // Create new profile object in appState
      appState.profile = {
        name,
        age,
        gender,
        height,
        weight,
        activityLevel: activityVal,
        goal: goalVal,
        metrics
      };

      // Add profile weight to weight logs if empty or new weight
      const todayStr = new Date().toISOString().split('T')[0];
      const weightLogExists = appState.weightLogs.find(l => l.date === todayStr);
      if (!weightLogExists) {
        appState.weightLogs.push({ weight, date: todayStr });
      } else {
        weightLogExists.weight = weight; // Update today's weight log
      }

      // Reset custom routine if the goal has changed
      appState.customRoutine = generateWorkoutRoutine(goalVal);

      saveState();
      updateUI();
      displayProfileSummary();
    }

    if (currentStep < steps.length - 1) {
      currentStep++;
      updateWizardState();
    } else {
      // Completed Wizard!
      saveState();
      updateUI();
      alert("Profile configured successfully! Welcome to HealthVerse AI.");
      switchView('dashboard-panel');
      currentStep = 0; // Reset wizard to index 0 for next edits
      updateWizardState();
    }
  };

  updateWizardState();
}

function displayProfileSummary() {
  if (!appState.profile) return;

  const m = appState.profile.metrics;
  document.getElementById('sum-bmi').textContent = m.bmi;
  document.getElementById('sum-bmr').textContent = `${m.bmr} kcal`;
  document.getElementById('sum-tdee').textContent = `${m.tdee} kcal`;
  document.getElementById('sum-target-cal').textContent = `${m.targetCalories} kcal`;
  
  document.getElementById('sum-target-p').textContent = `${m.targetProtein}g`;
  document.getElementById('sum-target-c').textContent = `${m.targetCarbs}g`;
  document.getElementById('sum-target-f').textContent = `${m.targetFats}g`;

  // BMI status evaluation
  let status = 'Normal';
  let color = 'var(--color-success)';
  if (m.bmi < 18.5) {
    status = 'Underweight';
    color = 'var(--color-warning)';
  } else if (m.bmi >= 25 && m.bmi < 30) {
    status = 'Overweight';
    color = 'var(--color-warning)';
  } else if (m.bmi >= 30) {
    status = 'Obese';
    color = 'var(--color-danger)';
  }

  const bmiStatusEl = document.getElementById('sum-bmi-status');
  bmiStatusEl.textContent = status;
  bmiStatusEl.style.color = color;
}

// Log current weight manually from Dashboard
function initWeightLogAction() {
  const logBtn = document.getElementById('dash-log-weight-btn');
  if (!logBtn) return;

  logBtn.onclick = () => {
    const inputVal = prompt("Enter your current weight (kg):", appState.profile ? appState.profile.weight : "");
    const weight = parseFloat(inputVal);

    if (isNaN(weight) || weight <= 10 || weight > 500) {
      if (inputVal !== null) alert("Please enter a valid weight between 10 and 500 kg.");
      return;
    }

    const todayStr = new Date().toISOString().split('T')[0];

    // Update weight logs
    const existingLog = appState.weightLogs.find(l => l.date === todayStr);
    if (existingLog) {
      existingLog.weight = weight;
    } else {
      appState.weightLogs.push({ weight, date: todayStr });
    }

    // Update profile weight
    if (appState.profile) {
      appState.profile.weight = weight;
      // Re-calculate profile metrics based on new weight
      appState.profile.metrics = calculateMetrics(
        appState.profile.age,
        appState.profile.gender,
        appState.profile.height,
        weight,
        appState.profile.activityLevel,
        appState.profile.goal
      );
    }

    saveState();
    updateUI();
    alert(`Weight logged: ${weight} kg. Metrics re-calculated!`);
  };
}


let webcamStream = null;

function initWebcamScanner() {
  const triggerBtn = document.getElementById('webcam-trigger-btn');
  const modal = document.getElementById('webcam-modal');
  const closeBtn = document.getElementById('webcam-close-btn');
  const captureBtn = document.getElementById('webcam-capture-btn');
  const video = document.getElementById('webcam-stream');

  if (!triggerBtn || !modal || !closeBtn || !captureBtn || !video) return;

  triggerBtn.addEventListener('click', async () => {
    try {
      webcamStream = await navigator.mediaDevices.getUserMedia({
        video: { facingMode: 'environment' },
        audio: false
      });
      video.srcObject = webcamStream;
      modal.style.display = 'flex';
    } catch (err) {
      console.error("Error accessing webcam:", err);
      alert("Unable to access camera. Please check camera permissions or upload an image instead.");
    }
  });

  const stopCamera = () => {
    if (webcamStream) {
      webcamStream.getTracks().forEach(track => track.stop());
      webcamStream = null;
    }
    video.srcObject = null;
    modal.style.display = 'none';
  };

  closeBtn.addEventListener('click', stopCamera);

  captureBtn.addEventListener('click', () => {
    const canvas = document.createElement('canvas');
    canvas.width = video.videoWidth || 640;
    canvas.height = video.videoHeight || 480;
    const ctx = canvas.getContext('2d');
    
    ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
    
    const dataUrl = canvas.toDataURL('image/png');
    stopCamera();
    
    showScannedPreview(dataUrl, "camera_capture_meal.png");
  });
}


// --- INITIALIZATION ENTRYPOINT ---

document.addEventListener('DOMContentLoaded', () => {
  // Load local state
  loadState();

  // Apply theme immediately
  applyTheme();

  // Navigation system
  setupNavigation();

  // Initialize tabs elements
  initOnboardingWizard();
  initMealScanner();
  initWeightLogAction();
  initThemeToggle();
  initWebcamScanner();

  // Attach Developer Reset Data button listener
  const resetBtn = document.getElementById('dev-reset-data-btn');
  if (resetBtn) {
    resetBtn.addEventListener('click', () => {
      if (confirm("Are you sure you want to reset all profile settings, historical charts, meal logs, and workouts? This action is irreversible.")) {
        resetAllData();
      }
    });
  }

  // Primary routing: if profile is not set, force user to onboarding, else dashboard
  if (!appState.profile) {
    switchView('profile-panel');
  } else {
    switchView('dashboard-panel');
  }

  // Draw initial UI items
  updateUI();

  // Initialize Lucide Icons
  lucide.createIcons();
});
